### ISSUE TITLE
Confusing superscript minus for relativistic orbitals?

### ISSUE THREAD

**Issue by jagot** [JuliaAtoms/AtomicLevels.jl#21]
Currently, we print "two electrons in the p subshell with spin down" as `2p⁻²`. This could be confused with the hole notation, where this means "two holes in the p subshell". Maybe we should make the relativistic, spin down label a subscript instead?

**Comment by mortenpi** [comment]
One option would be to just have a normal minus sign: `2p-²` vs `2p₋²` vs `2p⁻²`. Subscript would be consistent with the standard `p_½` notation though.

**Comment by mortenpi** [comment]
Just to push this towards a decision: I think it would be good to change this. I would vote for the normal minus sign though, not the subscript. @jagot, which option are you partial to?

**Comment by jagot** [comment]
I'm not really fond of the normal minutes either, but the subscript would clash with negative `m_j`s when we do relativistic spin-orbitals, so minus it is!

**Comment by jagot** [comment]
Implemented in 1a7af4ec32619d24ec3f33f78d6642d5ca5b4443.
