### ISSUE TITLE
String macros for spin-orbitals and spin-configurations

### ISSUE THREAD

**Issue by jagot** [JuliaAtoms/AtomicLevels.jl#41]
I find that I miss these from time to time, i.e. `so"1s0α"` and `sc"1s0α 2p-1β"`, or something along those lines. Ties in with #24 and #36. #21 should probably be resolved before, to reduce confusion (alternative notation for the m quantum number of a spin-orbital could be e.g. `sc"2p(-1)β"`).

**Comment by mortenpi** [comment]
The macro for orbitals was added in #88, but a macro for configurations is still on the TODO?

**Comment by jagot** [comment]
That's right; I wanted to generalize the current functionality for parse strings into configurations:
https://github.com/JuliaAtoms/AtomicLevels.jl/blob/07120dc9790651306c2c1ca4b03d38a251854066/src/configurations.jl#L345-L363
to work with spin-configurations as well, but I got a bit stuck.
