### ISSUE TITLE
IntermediateTerm: propertyname ambiguous on nightly

### ISSUE THREAD

**Issue by jagot** [JuliaAtoms/AtomicLevels.jl#76]
https://github.com/JuliaAtoms/AtomicLevels.jl/blob/1839efa90621531caebcdaead11418707c6dda5a/src/intermediate_terms.jl#L104-L114

See https://ci.appveyor.com/project/JuliaAtoms/atomiclevels-jl/builds/38205396/job/t77509gty37xrvnu#L160 (apparently we have run out of "Free Credits" on Travis, and need to apply for https://docs.travis-ci.com/user/billing-faq/#what-if-i-am-building-open-source, or switch to Github Actions).

**Comment by mortenpi** [comment]
> or switch to Github Actions

I would advocate for that option.

**Comment by mortenpi** [comment]
X-ref: https://github.com/JuliaLang/julia/pull/37550
