### ISSUE TITLE
Export kappa-ℓj conversion functions

### ISSUE THREAD

**Issue by mortenpi** [JuliaAtoms/AtomicLevels.jl#94]
Specifically: `kappa_to_j`, `kappa_to_ℓ` and `ℓj_to_kappa`. I use them quite often, but they are not currently part of the public API. We wouldn't necessarily have to export them actually -- just declaring them to be part of the public API would be sufficient.

Any thoughts @jagot? Name bikeshedding for them might be in order.

**Comment by jagot** [comment]
How about `κ2j`, `κ2ℓ`, and `ℓj2κ`? This would be consistent with [jj2lsj](https://github.com/JuliaAtoms/AtomicLevels.jl/blob/master/src/jj2lsj.jl) and Unicode On All The Things (`jj2lsj` should of course be `jj2ℓsj`, we can change that and `@deprecate` the old name).
